run:
  concurrency: 4
  timeout: 5m

linters:
  enable-all: true
  disable:
    - scopelint
    - exhaustivestruct
    - maligned
    - interfacer
    - golint
    - bodyclose
    - contextcheck
    - execinquery
    - paralleltest
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign
    - varnamelen
    - forbidigo
    - ireturn
    - exhaustruct
    - wrapcheck
    - testpackage
    - nlreturn
    - godox
